all:
	scp /home/kimteddy/EmbeddedSystem/opengl-egl-test/egltest.tar.gz ecube@192.168.207.19:~/teddy/egltest/
	#scp /home/kimteddy/EmbeddedSystem/opengl-egl-test/egltest/ ecube@192.168.207.19:~/teddy/egltest/