all: 
	#scp ./OpenGL-project/linux.cpp ecube@192.168.0.170:~/teddy/
	#scp ./OpenGL-project/Makefile ecube@192.168.0.170:~/teddy/

	scp ./OpenGL-project/linux.cpp ecube@192.168.207.19:~/teddy/disptest/
	scp ./OpenGL-project/Makefile ecube@192.168.207.19:~/teddy/disptest/
	scp ./OpenGL-project/simuwork.h ecube@192.168.207.19:~/teddy/disptest/
	scp ./OpenGL-project/libfbdev/libfbdev.c ecube@192.168.207.19:~/teddy/disptest/
	scp ./OpenGL-project/libfbdev/libfbdev.h ecube@192.168.207.19:~/teddy/disptest/
	scp ./OpenGL-project/libbmp/bitmapFileHeader.h ecube@192.168.207.19:~/teddy/disptest/