all: 
	scp ./OpenGL-project/linux.cpp ecube@192.168.0.170:~/teddy/
	scp ./OpenGL-project/Makefile ecube@192.168.0.170:~/teddy/

	scp ./OpenGL-project/linux.cpp ecube@192.168.46.19:~/teddy/
	scp ./OpenGL-project/Makefile ecube@192.168.46.19:~/teddy/